version: '3.9'

services:
  web:
    build: .
    image: anhkhoa01010902/kai_t367_statewebv3:v1.2  # Image sẽ được push lên Docker Hub
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Đồng bộ mã nguồn
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000
